# Generated by Django 5.2.6 on 2025-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="otp_type",
            field=models.CharField(
                choices=[("email_verification", "Email Verification"), ("password_reset", "Password Reset")], max_length=20
            ),
        ),
    ]
